#!/usr/bin/expect
set timeout 5

################# Get decrypted values of server, user and password at run time ###############################
set server NGUKSVAMDS287
set password "[exec /oracle/NRN/script/TEST/Passwd.sh]"
set username klal2

################# Execute remote server job ####################################################################
spawn sh -c "ssh -oStrictHostKeyChecking=no -oCheckHostIP=no $username@$server"
expect "*?assword"
send "$password\r"
expect "$"
################################################################################################################
