#!/usr/bin/expect
set timeout 20

################# Set variables ###############################
set server <your server name or IP>
set password <remote OS user password>
set username <remote OS user name>

################# Execute remote server command in a automatic way #############################################
spawn sh -c "ssh -oStrictHostKeyChecking=no -oCheckHostIP=no $username@$server ps -ef|grep pmon|grep ora|grep -v grep"
expect "*?assword"
send "$password\r"
expect eof
################################################################################################################