#!/usr/bin/expect
set timeout 5

################# Set variables ###############################
set server <your server name or IP>
set password <remote OS user password>
set username <remote OS user name>

################# Automated login to the remote server  #######################################################
spawn sh -c "ssh -oStrictHostKeyChecking=no -oCheckHostIP=no $username@$server"
expect "*?assword"
send "$password\r"
expect "$"
################################################################################################################
